### ISSUE TITLE
CitiesHarmony.API misuse (TypeLoadException on load)

### ISSUE THREAD

**Issue by drok** [rcav8tr/PopulationDemographics#2]
Hi again,

This bug is related to Harmony use, but it happens for a different reason, at a different point in the mod loading process. Technical details are at drok/Harmony-CitiesSkylines#8

The exception window **AN ERROR HAS OCCURRED** is shown on city load. It reads:

```
The Mod D:\Users\Radu\AppData\Local\Colossal Order\Cities_Skylines\Addons\Mods\PopulationDemographics [CitiesHarmony.API.dll, PopulationDemographics.dll] has caused an error [ModException]

Details:
System.TypeLoadException: A type load exception has occurred.
  at LoadingWrapper.OnLevelLoaded (UpdateMode mode) [0x00000] in <filename unknown>:0 
```

**Comment by rcav8tr** [comment]
Updated to gracefully handle missing Harmony mod.
